name: multivendor_seller
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0

  firebase_auth: ^1.0.1
  firebase_storage: ^8.0.0
  cloud_firestore: ^1.0.1
  firebase_core: ^1.0.1
  flutter_svg: ^0.21.0+1
  font_awesome_flutter: ^8.12.0
  flutter_share: ^1.0.5
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^9.4.1
  flutter_bloc: ^7.0.0
  carousel_pro: ^1.0.0
  full_screen_image: ^1.0.2
  extended_image: ^3.0.0
  flutter_switch: ^0.2.2
  image_picker: ^0.7.3
  image_cropper: ^1.4.0
  uuid: ^3.0.1
  flushbar: ^1.10.4
  http: ^0.13.0
  shared_preferences: ^2.0.4
  shimmer: ^1.1.2
  flutter_shimmer: ^1.3.0
  open_appstore: ^1.0.2
  flutter_datetime_picker: ^1.4.0
  excel: ^2.0.0-null-safety
  # permission_handler: ^6.0.0
  file_picker: ^3.0.1
  #google_map_location_picker:
  # git:
  #  url: git://github.com/davemg3/google_map_location_picker.git
  google_maps_flutter: ^2.1.3
  material_design_icons_flutter: ^5.0.6295
  minimize_app: ^0.1.1
  styled_text: ^5.1.0
  geocoding: ^2.0.0
  # geolocation: ^1.1.2
  geolocator: ^7.0.3

dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/banners/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
